### ISSUE TITLE
A Status page site api link 

### ISSUE THREAD

**Issue by Piecord** [avaire/avaire#102]
Feature it goes to statuspage.io  and then triggers when the bot is down a outrage status

**Comment by Senither** [comment]
This feature already exists and is hosted at [status.avairebot.com](https://status.avairebot.com/).
You can find the source code at [avaire/status](https://github.com/avaire/status).

If you have something you wish was added to that site, please open an issue in the [avaire/status](https://github.com/avaire/status) repository.
