### ISSUE TITLE
Dice command is broken

### ISSUE THREAD

**Issue by LavaTheif** [avaire/avaire#3]
>dice 4D8 doesnt work

**Comment by Senither** [comment]
https://media.senither.com/DQi9bqXQ0
![Dice Command](https://media.senither.com/DQi9bqXQ0 "Dice Command Example")

Seems to work fine? Are you self-hosting Ava or are you using the public version?

**Comment by LavaTheif** [comment]
Ohh I was doing it with a capital D
![screenshot_20180107-013736](https://user-images.githubusercontent.com/15127313/34645658-6ed2f014-f34b-11e7-88b2-927716817e47.png)
Could you maybe call .toLowerCase() on it? Since in the explaining thing its a capital

**Comment by LavaTheif** [comment]
Its my friend using it btw so it wont be self hosted they wouldnt know how to do that

**Comment by Senither** [comment]
Oh, yeah that's a bug, cheers for letting me know, I'll fix it in the next update, should update the bot sometime within the next 12 hours.

**Comment by Senither** [comment]
I pushed out the commit, should be fixed in [10b4874](https://github.com/avaire/avaire/commit/616921f9d2453108e74e78988559fd95d5dd8841), thanks again for letting me know^^ I'll update the live bot sometime in the next 12 hours so you'll get the update.

**Comment by LavaTheif** [comment]
Awsome! I'm loving the bot so far and can't wait to see all the new features you will add

**Comment by Senither** [comment]
Closing the issue since the bug has been resolved.
