### ISSUE TITLE
[HEROKU] Plugin support

### ISSUE THREAD

**Issue by Macley-Kun** [avaire/avaire#56]
## General Troubleshooting
- x I have checked for similar issues.
- x I have updated to the [latest Ava version][version].
- x I have checked the branches or the maintainers' PRs for upcoming features/bug fixes.

## Issue
General issues/features that are missing when using AvaIre on Heroku.

### Issue Type
- x Bug Report
- x Feature Request

### Description
AvaIre runs now on Heroku fine. A normal user can interact with her, and can also change the env variables on the fly. Making it a worthy choice compared to traditional solutions.

However, some issues/features are yet to be fixed/implemented. The following are yet to be implemented/fixed:
- [x] Plugin support. As of now, adding plugins can't be done directly with the deployed template. You can, however, make a fork, add the plugins yourself, and deploy that. [Senither already suggested using environment variables for this too](https://github.com/avaire/avaire/pull/53#discussion_r234356455). Even tho he suggests this for watchdog. It could be used in AvaIre aswell.
- [x] Using the API. As of now, AvaIre uses a WORKER dyno. To get the API working, the jetty server has to somehow connect to the port, that is given by the web dyno. As [these docs](https://devcenter.heroku.com/articles/java-webapp-runner) suggest. If this works, AvaIre's stats are then exposed, what can be used to run the [avaire/status](https://github.com/avaire/status) project. Or a minimal, self-made music dashboard for example.
- [x] ~~Cleaning the build files that Gradle creates after compiling on Heroku. As of now, when Heroku is done compiling with Gradle. It leaves the build artifacts, what increases the total slug size to 307mb (as of now). Heroku suggests using under 300mb to not affect boot time to much. The lower this number is, the faster AvaIre will startup. You cannot use the [.slugignore](https://devcenter.heroku.com/articles/slug-compiler#ignoring-files-with-slugignore), as this is used before de buildpacks. It's explicitly after the last buildpack, that this happens. Possibly, some script could be run to clean. I'm thinking of using [this buildpack](https://elements.heroku.com/buildpacks/itsdamien/heroku-buildpack-run). And adding lines that delete the build artifacts.~~
- [x] ~~Support of using mysql string, like: `mysql://drf92r47agqzea9k:c83wl6ot8sbtmuvd@r6ze0q02l4me77k3.chr7pe7iynqr.eu-west-1.rds.amazonaws.com:3306/mbyaga9t3h70nls9`. But most importantly that this string can be used, using the env variable name: `JAWSDB_URL`. IF, this will be implemented into AvaIre. Users no longer need to set anything themselfs after deploying. Making deploying the easiest way possible. As only copying and pasting the api/token/etc into the template and hitting deploy is then needed.~~

**Comment by Macley-Kun** [comment]
I think the biggest issue with this issue is that the plugin jar has to be added during it's build phase.

Optionally, we could have the plugin be re-downloaded everything it starts what would be fine.
Configurations would have to be stored in the database. Maybe this has then become a duplicate of #37?

**Comment by Macley-Kun** [comment]
Up to you to close it :P 
Personally i would wait that filling in credentials is implemented. But hey it's you party! 😄

**Comment by Senither** [comment]
I'm gonna go ahead and close the issue since everything on the TODO list for the system have already been implemented, the config editing system is only really necessary for systems like Heroku where the filesystem is reset on each boot, any other hosting service would still allow self-hosters to edit the plugin configs.

In regards to the plugin config editing system, I'll most likely implement it through a plugin since it's not necessarily something everyone would want to use, so people could install the plugin through the new plugin system, and then use it to overwrite values in other plugins configs, there are still some complications with actually being able to do that however, so gotta sort that out before I can even start on the project.

**Comment by Macley-Kun** [comment]
Sure sounds great! Meanwhile users can just create the config file themselves :3

Outlook voor iOS<https://aka.ms/o0ukef> downloaden

________________________________
Van: Alexis Tan <notifications@github.com>
Verzonden: donderdag, november 14, 2019 1:25 PM
Aan: avaire/avaire
CC: Macley; Author
Onderwerp: Re: [avaire/avaire] [HEROKU] Plugin support (#56)


Closed #56<https://github.com/avaire/avaire/issues/56>.
